### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Lorenzo-Martinez** [lamc8684/McIntire_CSCI2270_FinalProject#2]
I know that there are descriptions of what the methods do in the README, but there is only one comment block in the Tree.cpp file that includes the function prototype, function description, example, precondition, and postcondition.

**Comment by lamc8684** [comment]
I was going to tell you to take a look at https://github.com/AlexChido/VallinRomo_CSCI2270_FinalProject where we decided to keep everything after all, but it seems you've already noticed. Thanks for your patience :)
